---
title: "Syllabus"
output:
  html_document:
    includes:
      after_body: include/nothing.html
---

```{r include = FALSE}
library(dplyr)
library(stringr)
```

```{r include = FALSE}
#Class meetings
rawdat_cm <- read.csv(file.path("course-admin", "class-meetings.csv"),
                   stringsAsFactors = FALSE,
                   colClasses = list(course = 'factor', dow = 'factor'))
cdat <- rawdat_cm %>%
  mutate(ugly_date = ISOdate(2014, match(month, tolower(month.name)), day),
         date = sprintf("%s-%02d %s",
                        tolower(months(ugly_date, abbreviate = TRUE)),
                        day, dow),
         notes = ifelse(grepl("^cm", cm) & raw_notes != "",
                        sprintf("%s: %s", cm, raw_notes), raw_notes))
cdat %>% head(3)

## link to the class page of any class meetings where such exists
cmdat <-
  data.frame(html = list.files(pattern = '^cm.*html$'),
             stringsAsFactors = FALSE)
cmdat <- cmdat %>% mutate(cm = str_extract(html, "cm[0-9]+"))
cdat <- cdat %>% left_join(cmdat)

cdat <- cdat %>%
  mutate(html_exists = Negate(is.na)(html))
cdat$notes[cdat$html_exists] <-
  str_replace(cdat$notes[cdat$html_exists],
              "(cm[0-9]{3})", '<a href="LINK">\\1</a>')
cdat <- cdat %>% mutate(notes = str_replace(notes, "LINK", html))
dat_cm <- cdat %>% split(cdat$course)
dat_cm <- lapply(dat_cm, 'rownames<-', NULL)

#Seminar meetings
#Class meetings
rawdat_sm <- read.csv(file.path("course-admin", "seminar-meetings.csv"),
                   stringsAsFactors = FALSE,
                   colClasses = list(course = 'factor', dow = 'factor'))
sdat <- rawdat_sm %>%
  mutate(ugly_date = ISOdate(2014, match(month, tolower(month.name)), day),
         date = sprintf("%s-%02d %s",
                        tolower(months(ugly_date, abbreviate = TRUE)),
                        day, dow),
         notes = ifelse(grepl("^sm", sm) & raw_notes != "",
                        sprintf("%s: %s", sm, raw_notes), raw_notes))
sdat %>% head(3)

## link to the class page of any class meetings where such exists
smdat <-
  data.frame(html = list.files(pattern = '^sm.*html$'),
             stringsAsFactors = FALSE)
smdat <- smdat %>% mutate(sm = str_extract(html, "sm[0-9]+"))
sdat <- sdat %>% left_join(smdat)

sdat <- sdat %>%
  mutate(html_exists = Negate(is.na)(html))
sdat$notes[sdat$html_exists] <-
  str_replace(sdat$notes[sdat$html_exists],
              "(sm[0-9]{3})", '<a href="LINK">\\1</a>')
sdat <- sdat %>% mutate(notes = str_replace(notes, "LINK", html))
dat_sm <- sdat %>% split(sdat$course)
dat_sm <- lapply(dat_sm, 'rownames<-', NULL)
```

<!-- unholy hack to make following two tables less wide and the same wide -->
<style type="text/css">
table {
   max-width: 50%;
}
</style>

#### STAT 540: Class mettings

```{r results = 'asis', echo = FALSE}
knitr::kable(dat_cm[["STAT540"]] %>% select(date, notes, instructor))
```

#### STAT 540: Seminars

```{r results = 'asis', echo = FALSE}
knitr::kable(dat_sm[["STAT540-Seminar"]] %>% select(date, notes, TA))
```
