---
title: "How to organize your repository"
author: "Evan"
# date: '2015-01-19'
output: html_document
---

We would like you to submit your homework and seminars via your assigned Github repository. Because Github can visualize Markdown files and R Markdown (see [this link](http://stat540-ubc.github.io/sm02a_rMarkdown.html)), we want you submit content as md and Rmd files. However, it is important that your repository remain easy to navigate. You may use the default "README.md" to stylize your repository's homepage.

### How to make md files from Rmd files
Some versions of R Studio will automatically generate md files from Rmd files when you click "knit". However, some versions discard of the md after using it as an intermediary step. To enable md file retention, click on the little gear next to "knit", go to "Advanced", and check "Keep markdown source file".

### General layout
The basic repository layout consists of a homepage which has links to seminars and homework rendered Markdown files. An example can be found [here](https://github.com/wdurnoUBC/testRepo/tree/cd11f4d359294451a4cb6a89e38d9026e6721580).

### How to make links
The one most important Rmd syntax you must learn to stay organized is how to write URL links. In-text, one may write the following to create a link.
```
[link name](URL)
```

### Be creative!
I encourage you to be creative with your repository and use it to demonstrate your learning! However, please keep it organized so that everyone's work may be graded efficiently.

### Getting started
  * If you need help learning how to **write R Markdown** and turn it into Markdown, you can find a tutorial[here](http://stat545-ubc.github.io/block007_first-use-rmarkdown.html).
  * If you need help learning how to **interact with your online repository via Git**, you can find a tutorial [here](http://stat545-ubc.github.io/git07_git-usage.html).
  * [Connecting R Studio to Git on Windows](https://github.com/STAT540-UBC/STAT540-UBC.github.io/raw/master/howToRStudioGitWindows.pdf)
  * [Connecting R Studio to Git on Mac](https://github.com/STAT540-UBC/STAT540-UBC.github.io/raw/master/howToRStudioGitMac.pdf)
  * [Connecting R Studio to Git on Ubunutu](https://github.com/STAT540-UBC/STAT540-UBC.github.io/raw/master/howToRStudioGitUbuntu.pdf)
  