---
title: "Title of demonstration"
output:
  html_document:
    keep_md: yes
---
big header
==========

small header
------------

This document contains **formatted** *text*! You can write **math**!

$$L_AT^EX$$
$$1 = \mathbb{P} \left[ \Omega \right] 
= \mathbb{E} \left[ 1_{\{ \omega \; : \; \Omega \; is \; well-ordered \}} \right]
\Leftarrow Ax. \; Choice$$
$$\left[ \forall n \in \mathbb{N}, x \geq y \Rightarrow f_n(x) \geq f_n(y) \right] \Rightarrow \lim_{n \rightarrow \infty}\sum_{\alpha \in X} \alpha f_n(\alpha) = \sum_{\alpha \in X} \alpha \lim_{n \rightarrow \infty} f_n(\alpha)$$

The R code **runs** when the document **compiles**. *The image is generated after the code runs!*

```{r}
X = function(A=1,B=-2,C=-1.5,D=-3,n=1000)
{
  dt = 1/n
  dX = (A + B*(1:n)*dt)*dt + exp( C + D*(1:n)*dt ) * sqrt(dt) * rnorm(n)
  return( cumsum(dX) )
}
library("graphics")
clr = rainbow(100)
plot(X(),type='l',xlab="t",ylim=c(-0.2,0.5),main="R plots in documents are amazing!")
H = matrix( nrow = 100 , ncol = 1000 )
for( i in 1:100 ){ H[i,] = X() }
idx = sort(H[,1000],index.return=T)
H = H[ idx$ix , ]
for( i in 1:100 )
  {lines( H[i,] , type='l' , col=clr[i] )}
```

more tricks
-----------

```{r}
# This code runs
1+3
```

```
# This code does not run
1+3
```

* bullet
* points
* are 
* great

1. numbered
2. lists
3. are 
4. good 
5. too

> But sometimes
> it is better 
> to simply 
> quote text
